#!/usr/bin/env node
/* Prints the SQL that makes the database's price list match the client's.
   The server decides what things cost now, so a prop added to src/props.js
   without its row here cannot be bought. Run it after changing the catalogue
   and apply the output:

     node tools/catalogue-sql.js > docs/migrations/catalogue.sql

   Prices only ever come from src/props.js and src/diorama.js, so there is one
   place to change a price and this is not it. */
"use strict";
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const props = fs.readFileSync(path.join(ROOT, "src", "props.js"), "utf8");
const diorama = fs.readFileSync(path.join(ROOT, "src", "diorama.js"), "utf8");

const items = [...props.matchAll(
  /\{\s*id:"([a-z0-9]+)",\s*name:"[^"]+",\s*price:(\d+),\s*charm:(\d+),\s*w:\d+,\s*h:\d+,\s*room:"([a-z]+)"(,\s*memento:true)?/g)]
  .map(m => ({ id:m[1], price:+m[2], charm:+m[3], room:m[4], memento:!!m[5] }));
const rooms = [...diorama.matchAll(/\{ id:"([a-z]+)",\s*name:"[^"]+",.*?price:\s*(\d+)/g)]
  .map(m => ({ id:m[1], price:+m[2] }));

if(!items.length || !rooms.length) throw new Error("could not read the catalogue");
const ids = new Set();
items.forEach(i => { if(ids.has(i.id)) throw new Error("duplicate item id " + i.id); ids.add(i.id); });

const q = s => "'" + String(s).replace(/'/g, "''") + "'";
console.log("/* generated by tools/catalogue-sql.js: " + items.length + " items, " + rooms.length + " rooms */");
console.log("insert into public.room_prices (id, price) values\n  " +
  rooms.map(r => "(" + q(r.id) + ", " + r.price + ")").join(",\n  ") +
  "\non conflict (id) do update set price = excluded.price;");
console.log("insert into public.catalogue_items (id, room, price, charm, memento) values\n  " +
  items.map(i => "(" + [q(i.id), q(i.room), i.price, i.charm, i.memento].join(", ") + ")").join(",\n  ") +
  "\non conflict (id) do update set room = excluded.room, price = excluded.price,\n" +
  "  charm = excluded.charm, memento = excluded.memento;");
